export { Header } from "./Header";
export { Footer } from "./Footer";
export { Home } from "./Home";
export { Catalogue } from "./Catalogue";
export { Cool } from "./Cool";
export { Holidays } from "./Holidays";
export { Boxes } from "./Boxes";
export { News } from "./News";
export { About }  from "./About";